# Generated by Django 5.0.7 on 2024-07-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure_date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('stopovers', models.BooleanField(default=False)),
                ('special_offer', models.BooleanField(default=False)),
                ('additional_details', models.TextField()),
                ('transport_type', models.CharField(choices=[('airplane', 'Airplane'), ('train', 'Train'), ('cruise', 'Cruise')], max_length=10)),
            ],
        ),
    ]
