# Generated by Django 5.0.7 on 2024-07-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='transport_type',
            field=models.CharField(choices=[('airplane', 'Airplane')], max_length=10),
        ),
    ]
